### ISSUE TITLE
Tower 'Hole' not creating hole

### ISSUE THREAD

**Issue by srwaggon** [srwaggon/minecraft-roguelike#32]
Great work!

From what I can tell, things are in order now, apart from the `hole` tower--which you were right, `hole` seems to be the only tower that isn't working, the others seem fine.

Indeed `hole` is, in version `1.12.2-2.1.4`, creating a pit as you recall (it's very nice for hiding smaller dungeons!). Here's what they're looking like on my end:
![RoguelikeTowerHole1](https://user-images.githubusercontent.com/74480944/105012731-13978c00-5a04-11eb-8596-ceea5c165b85.gif)
Generated by this dungeon json, in `1.12.2-2.1.4`:
```
{
  "name": "dungeon:cave",
  "exclusive": true,
  "inherit": [
    "layout:size_small",
	
    "tower:hole",
    "theme:cave",

    "filter:muddy",
    "filter:viney",

    "demo:rooms",
    "dungeon:common"
  ]
}
```

_Originally posted by @Ameranth in https://github.com/srwaggon/minecraft-roguelike/issues/29#issuecomment-762707985_

**Comment by srwaggon** [comment]
Verified working on commit 406eecb1

**Comment by srwaggon** [comment]
Thanks again @Ameranth. Your excellent report lead to a timely fix. This issue was also causing problems for other towers, so it was a superb find. The fix was literally one word -- the word "this".

The release .jar has been updated again. 🙂Enjoy.

**Comment by Ameranth** [comment]
Haha! Excellent work, I'm ecstatic to have helped!

So far I haven't seen any issues with the new .jar, so I'll continue using it and let you know if anything else comes up.

**Comment by Ameranth** [comment]
Sadly it seems I spoke too soon; in the new alpha build I've noticed the themes `theme:forest` and `demo:theme` preventing towers/staircases from generating. I tried to investigate these themes to see if I could pinpoint the problem--as dungeons inheriting from builtins appear to work fine--but I'm sorry to say I couldn't figure it out yet.

**Comment by srwaggon** [comment]
@Ameranth You're in luck! I spotted those problems as well.

The forest dungeons were failing to generate towers for me because they were referencing modded mobs & blocks while running in vanilla forge.

The stair casing issue is from the refactoring for 1.14 and has also been addressed (here: https://github.com/srwaggon/minecraft-roguelike/commit/fa3ee70f4669ac9003d82446959b698cf6ee82d7).

Once again, the latest build jar has been uploaded to the release (https://github.com/srwaggon/minecraft-roguelike/releases/tag/v2.2.1). Hopefully I'll automate this soon.

I've also taken the time to clean and modify the dungeon settings from my modded world and upload them as part of this repo (here: https://github.com/srwaggon/minecraft-roguelike/tree/master/roguelike-core/src/main/resources/settings). Hopefully these are easier to work with and don't create more work for you!

I seriously cannot thank you enough for your thorough investigation and communication. Happy adventuring!

**Comment by Ameranth** [comment]
@srwaggon Thank you again!

I tried out the new version, but I'm crashing on starting a new world with it; I also tried with your repo settings as well as without any settings at all (clean install), but it crashed nonetheless :(

Here's the crash:
```
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/JsonProcessingException
    at greymerk.roguelike.dungeon.settings.SettingsContainer.<init>(SettingsContainer.java:39)
    at greymerk.roguelike.dungeon.settings.SettingsResolver.initSettingsResolver(SettingsResolver.java:56)
    at greymerk.roguelike.dungeon.Dungeon.initResolver(Dungeon.java:60)
    at greymerk.roguelike.dungeon.Dungeon.<clinit>(Dungeon.java:45)
    at com.github.srwaggon.roguelike.worldgen.DungeonGenerator.generate(DungeonGenerator.java:20)
    at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:167)
    at net.minecraft.world.chunk.Chunk.populate(Chunk.java:1020)
    at net.minecraft.world.chunk.Chunk.populate(Chunk.java:999)
    at net.minecraft.world.gen.ChunkProviderServer.provideChunk(ChunkProviderServer.java:157)
    at net.minecraft.server.MinecraftServer.initialWorldChunkLoad(MinecraftServer.java:344)
    at net.minecraft.server.integrated.IntegratedServer.loadAllWorlds(IntegratedServer.java:210)
    at net.minecraft.server.integrated.IntegratedServer.init(IntegratedServer.java:233)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.core.JsonProcessingException
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 14 more
Caused by: java.lang.NullPointerException
```
