### ISSUE TITLE
Crashlog by LUEZIS (on world startup)

### ISSUE THREAD

**Issue by LUEZIS** [srwaggon/minecraft-roguelike#9]
[crash-2020-04-08_18.21.12-server.zip](https://github.com/srwaggon/minecraft-roguelike/files/4452415/crash-2020-04-08_18.21.12-server.zip)

**Comment by srwaggon** [comment]
Thanks a ton, @LUEZIS .

Attached crash log from LEUZIS
https://pastebin.com/3TZhrGkY

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  Thaumic Augmentation Core Plugin (ThaumicAugmentation-1.12.2-1.1.17.jar)
  ItemPatchingLoader (ItemPhysic_Full_1.4.32_mc1.12.2.jar)
  AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
  Quark Plugin (Quark-r1.6-179.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-92.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.5.10-core.jar)
  BetterFoliageLoader (BetterFoliage-MC1.12-2.3.1.jar)
  PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50-universal.jar)
  MMFMLCorePlugin (MultiMine-1.12.2.jar)
  JustEnoughIDs Extension Plugin (JustEnoughIDs-1.0.3-55.jar)
  BewitchmentFMLLoadingPlugin (bewitchment-1.12.2-0.0.21.11.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  ratscore (rats-3.2.8.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.151.jar)
  TransformLoader (DynamicSurroundings-1.12.2-3.6.1.0.jar)
  SSLoadingPlugin (SereneSeasons-1.12.2-1.2.18-universal.jar)
  TenshiCore (TenshiLib-1.12.2-1.2.3.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  ShoulderPlugin (ShoulderSurfing-1.12.2-1.15.1.jar)
  HCASM (HammerLib-1.12.2-2.0.6.14.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  Techguns Core (techguns-1.12.2-2.0.2.0_pre3.1.jar)
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.10-1.12.2.jar)
  CreativePatchingLoader (CreativeCore_v1.10.10_mc1.12.2.jar)
  GSHooksLoader (GalaxySpace-1.12.2-2.0.12.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.244.jar)
Contact their authors BEFORE contacting forge

// Hey, that tickles! Hehehe!

Time: 4/8/20 5:40 PM
Description: Exception in server tick loop

java.lang.NoSuchFieldError: WOOD
	at greymerk.roguelike.worldgen.WorldEditor.<clinit>(WorldEditor.java:34)
	at greymerk.roguelike.DungeonGenerator.generate(DungeonGenerator.java:19)
	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:167)
	at micdoodle8.mods.galacticraft.core.TransformerHooks.otherModGenerate(TransformerHooks.java:198)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1020)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:999)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:344)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:210)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:233)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by srwaggon** [comment]
@LUEZIS , you also mentioned that Galacticraft is at fault. Can you say anymore about that?

**Comment by srwaggon** [comment]
It seems like Roguelike is expecting WOOD to exist, provided by Minecraft, but that it can't find it. I'm unsure what would remove WOOD from Minecraft.

**Comment by srwaggon** [comment]
Certain mods edit or remove wood. This mod depends on wood. I've heard that this is specifically a problem with Galacticraft. Closing for now as there's no real fix. Happy to re-open if another solution is offered or this causes serious grief.
